### ISSUE TITLE
Update Downloads section

### ISSUE THREAD

**Issue by BGMP** [Re-Volt-America/Website#9]
Should add the missing dowloads to the base version of the game, and also some instructions on the installation procedure

**Comment by EstebanMz** [comment]
I came here to write the same jajaj
Yeah, instead of redirect to RVGL website, where a user will have to look for a new download link, which will download an "uncomplete" version of Re-Volt; it would be better to show direct links to download _re-volt original_ for windows and android for example. I'm talking about the [https://distribute.re-volt.io/](links here)

**Comment by BGMP** [comment]
@EstebanMz I've updated the downloads section in https://github.com/Re-Volt-America/Website/commit/1fc27b441f7da1c288312477cd037b32d135e69d.

I'm unsure about including downloads for the original game as I believe having RVGL + RVA should be more than enough. What really is missing however are downloads for macOS, Linux & Android in this exact same format -- after finishing those off we should be done with the dowloads page.

  * https://distribute.revolt-america.com/ is now the file listing mirror of our distribution effort.
  * https://revolt-america.com/downloads the updated downloads page.
 
### TODO:

- [ ] Add Linux downloads (RVGL + RVA).
- [ ] Add macOS downloads (RVGL + RVA).
- [ ] Add Android downloads (RVGL + RVA).

**Comment by BGMP** [comment]
Due to the RVGL Launcher being the current recommended way of managing custom content packs, this issue no longer serves any purpose, as full downloads have become the not-recommended way of downloading and maintaining the game.
